FROM ghcr.io/felladrin/minisearch:main

ARG INTERNAL_OPENAI_COMPATIBLE_API_BASE_URL
ARG INTERNAL_OPENAI_COMPATIBLE_API_MODEL
ARG INTERNAL_OPENAI_COMPATIBLE_API_NAME
ARG DEFAULT_INFERENCE_TYPE
ARG ACCESS_KEYS
ARG ACCESS_KEY_TIMEOUT_HOURS
ARG INTERNAL_OPENAI_COMPATIBLE_API_KEY
ARG ALLOWED_HOSTS
